# Generated by Django 5.2.8 on 2025-11-26 09:05

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayStrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_point', models.CharField(max_length=50, unique=True)),
                ('grammar_summary', models.CharField(max_length=500)),
                ('rule_1', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('rule_2', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('rule_3', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('rule_4', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('situation_1', models.CharField(blank=True, max_length=500, null=True)),
                ('situation_2', models.CharField(blank=True, max_length=500, null=True)),
                ('situation_3', models.CharField(blank=True, max_length=500, null=True)),
                ('situation_4', models.CharField(blank=True, max_length=500, null=True)),
                ('example_1', models.CharField(blank=True, max_length=500, null=True)),
                ('example_2', models.CharField(blank=True, max_length=500, null=True)),
                ('example_3', models.CharField(blank=True, max_length=500, null=True)),
                ('example_4', models.CharField(blank=True, max_length=500, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.daystrick')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.daystrick')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='speaking/')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.daystrick')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=100, unique=True)),
                ('pinyin', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=150)),
                ('example', models.CharField(blank=True, max_length=300, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.daystrick')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=300)),
                ('pinyin', models.CharField(blank=True, max_length=500, null=True)),
                ('meaning', models.CharField(blank=True, max_length=500, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.daystrick')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.vocabulary')),
            ],
        ),
    ]
