# Generated by Django 5.2.8 on 2025-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='rule_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='rule_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='rule_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='rule_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
