# Generated by Django 5.2.8 on 2025-11-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_grammar_rule_1_alter_grammar_rule_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystrick',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
