# Generated by Django 5.2.8 on 2025-12-05 06:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_daystrick_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingpractice',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
