# Generated by Django 5.2.8 on 2026-01-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_readingpractice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystrick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
