# Generated by Django 5.2.8 on 2026-01-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_daystrick_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='example_1',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example_2',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example_3',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='example_4',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='rule_1',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='rule_2',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='rule_3',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='rule_4',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='situation_1',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='situation_2',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='situation_3',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='situation_4',
        ),
        migrations.AlterField(
            model_name='daystrick',
            name='day',
            field=models.DateTimeField(auto_now_add=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, max_length=200, null=True)),
                ('situation', models.CharField(blank=True, max_length=500, null=True)),
                ('example', models.CharField(blank=True, max_length=500, null=True)),
                ('grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='academy.grammar')),
            ],
        ),
    ]
