# Generated by Django 5.2.8 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_remove_grammar_example_1_remove_grammar_example_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystrick',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
