# Generated by Django 5.2.8 on 2026-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_daystrick_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystrick',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='daystrick',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='daystrick',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
