# Generated by Django 5.2.8 on 2026-01-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesentences',
            name='sentence',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
